# Generated by Django 5.2.3 on 2025-07-07 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SparePartTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_description', models.TextField()),
                ('previous_hash', models.CharField(blank=True, max_length=64)),
                ('current_hash', models.CharField(blank=True, max_length=64)),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traces', to='inventory.sparepart')),
            ],
        ),
    ]
