# Generated by Django 5.2.3 on 2025-08-04 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_spareparttrace'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepart',
            name='quality',
            field=models.CharField(choices=[('ORIGINAL', 'Original'), ('ADAPTABLE', 'Adaptable'), ('NEUF', 'New'), ('OCCASION', 'Used')], default='NEUF', max_length=20),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='vendor_type',
            field=models.CharField(choices=[('Concessionnaire', 'Concessionnaire'), ('Equipementier', 'Equipementier'), ('Importateur', 'Importateur'), ('Grossiste', 'Grossiste'), ('Semi-grossiste', 'Semi-grossiste'), ('Détaillant', 'Détaillant'), ('Ferrailleurs', 'Ferrailleurs'), ('Particuliers', 'Particuliers (BtC to C)')], default='Grossiste', max_length=50),
        ),
    ]
